### ISSUE TITLE
Pokemon Go AR issues

### ISSUE THREAD

**Issue by ivy501** [google-ar/arcore-android-sdk#1122]
### SPECIFIC ISSUE ENCOUNTERED
Going into Pokémon GO and after clicking on a couple Pokémon pop up says ARcore needs to be updated. Clicking on ok takes you to Play store, but AR core is already updated. If AR is off and you turn it back on it will make the pop come up right away. Keeping the core off will cause the pop to show every time you click on a Pokémon.

### VERSIONS USED
- Android Studio: 
- ARCore SDK for Android: version 1.19.202100803
- Device manufacturer, model, and O/S: LG Stylo 6 10.0
- ARCore: 
  On Windows, use: `adb shell pm dump com.google.ar.core | findstr /i "packages: versionName"`
  On macOS, use: `adb shell pm dump com.google.ar.core | egrep -i versionName\|packages:`
- Output of `adb shell getprop ro.build.fingerprint`: 

### STEPS TO REPRODUCE THE ISSUE
 1. Turning it on from settings in Pokémon GO will cause pop up immediately
 1.
 1.

### WORKAROUNDS (IF ANY)
 Hitting cancel each time the pop up occurs make it so you can still catch the Pokémon, though keeps popping up.

**Comment by sandyfriend** [comment]
Could you provide more details.
ARCore:
On Windows, use: adb shell pm dump com.google.ar.core | findstr /i "packages: versionName"
On macOS, use: adb shell pm dump com.google.ar.core | egrep -i versionName\|packages:
Output of adb shell getprop ro.build.fingerprint:

**Comment by ivy501** [comment]
Needs another update do to software issues

**Comment by ivy501** [comment]
Below is a screenshot of the problem, it's been happening for about a
month now and my local cellphone store said it was a problem with the app,
my AR+ is updated all the way, I also tried uninstalling and reinstalling
the app a few times but nothing has worked, I saw a help page on Twitter
that you guys responded too so I tried disabling my ar+ for google but that
didnt work either, what do I do now?

**Comment by ivy501** [comment]
I play Pokemon daily it helps to keep me clean and sober I have 5 years
thanks to the help of Pokemon go. I am an ex heroin and methamphetamine
addict and Pokemon allows me to get out and exercise and keep me on the
right track im hopeing that we can work together on fixing the ar+core app
so I can continue playing the game. I play the game daily and with the
ar+core not working right it doesn't allow me to play as often.

**Comment by devbridie** [comment]
This has been fixed for some models of devices, and we're communicating with Niantic to get other devices fixed soon.

**Comment by ivy501** [comment]
I did another ar+ update and the pop-up still comes up I dont understand
why its still not working right what should i do?
