### ISSUE TITLE
All ar game's not working. arcore not working in game's

### ISSUE THREAD

**Issue by Grimsides** [google-ar/arcore-android-sdk#1135]
### SPECIFIC ISSUE ENCOUNTERED
All Ar game in Google play store dont work on my smartphone. 

### VERSIONS USED
- Android Studio: 
- ARCore SDK for Android: 1.19.202100823
- Device manufacturer, model, and O/S: LG, LM-Q630EA, android 9
- ARCore: 1.19.202100823

### STEPS TO REPRODUCE THE ISSUE
 1.1.all ar games show a black screen when connecting to ar function or camera.
![Capture+_2020-08-31-09-12-22](https://user-images.githubusercontent.com/71657621/93799503-89027400-fc3f-11ea-96ee-fb8a1b92ea19.png)
![Capture+_2020-09-21-17-19-44](https://user-images.githubusercontent.com/71657621/93799514-8acc3780-fc3f-11ea-9cfc-4af4efc227e9.png)
![Capture+_2020-09-21-17-42-58](https://user-images.githubusercontent.com/71657621/93799518-8b64ce00-fc3f-11ea-9569-6efd1562e9dd.png)
![Capture+_2020-08-31-09-12-49](https://user-images.githubusercontent.com/71657621/93799522-8bfd6480-fc3f-11ea-9209-3d096d2a4219.png)
Images of games
1.Pokemon go
2.knightfall
3. angry birds AR
4. Pokemon go
 1.2. some games a message cannot connect ar problem occurred.

### ADDITIONAL COMMENTS
Using a LG k61 have tryed 10 different games and all of them don't work. all intalled from Google play store have updated ARcore still the same problem. It on the arcore function.

**Comment by Grimsides** [comment]
It not just the ar games it ar apps to

**Comment by devbridie** [comment]
Thanks for reporting. We're aware of some problems with this particular device; I've asked for some clarification and will update this thread with some more information ASAP.

**Comment by Grimsides** [comment]
Ok thanks

**Comment by Grimsides** [comment]
Is there any info on this problem?

**Comment by KevinBrechtel** [comment]
LG support only provides info that "app is the reason, device is fine", but no app with AR content is working!

**Comment by devbridie** [comment]
It's my understanding that this has been fixed. If not, please let me know.

**Comment by xyrus02** [comment]
It is still not working on K61. What exactly has been done to fix it?
