### ISSUE TITLE
Config.FocusMode.AUTO not working

### ISSUE THREAD

**Issue by ThomasGorisse** [google-ar/arcore-android-sdk#1300]
Hi,

We have an issue with the Config.FocusMode.AUTO.

The focus is never made even the session is configured with the auto focus mode.
We have to resume the session twice in order to make it work.

It is also the case in the [augmented_image_java sample](https://github.com/google-ar/arcore-android-sdk/tree/master/samples/augmented_image_java).

Screencast and more infos here: https://github.com/ThomasGorisse/sceneform-android-sdk/issues/182

Thanks

**Comment by tydice** [comment]
Same issue with Samsung Galaxy S21+ and S21 Ultra.

**Comment by egorix** [comment]
Same applies to Samsung S10e.
Any updates on this bug?

**Comment by sandyfriend** [comment]
Internal Bug have been raised to related team.
Will updated if  it has more info.

temp walkaround,  
put the app to background and bring it back.

**Comment by ThomasGorisse** [comment]
Do you know if it can be solved as a configuration push, Google Play Services for AR update or a new ARCore SDK version?

**Comment by lorenzoSpacelens** [comment]
Possible workaround

`
            session.resume()
            session.pause()
            session.resume()
`

**Comment by kmayoral** [comment]
I see that this was labeled as fixed in upcoming release on January 27th, 2022. Since then, there have been 3 releases of the SDK. Was this fix included in one of those perhaps? Thank you for the fix and any clarification.

**Comment by softlion** [comment]
3 releases ? Much more than that. August 2023 and it is still not fixed.

Google abandoned Arcore.
