### ISSUE TITLE
java.lang.IllegalStateException: Image is already closed when calling image.getHardwareBuffer().

### ISSUE THREAD

**Issue by lxshao007** [google-ar/arcore-android-sdk#1578]
### SPECIFIC ISSUE ENCOUNTERED

in order to use filament with the latest stream API, I need to call image.getHardwareBuffer and pass that to filament engine. however, it gives the error java.lang.IllegalStateException: Image is already closed when calling image.getHardwareBuffer().

filament sample api use the camera 2 API. so I test the it in the shared camera, which has the camera 2 api access. it seems fine. 
is there is way we can use image.getHardwareBuffer() instead of the shared camera camera 2 API? 

this is my origin question on filament https://github.com/google/filament/issues/6748

### VERSIONS USED
- Android Studio: 
- ARCore SDK for Android: 
- Device manufacturer, model, and O/S: 
- Google Play Services for AR (ARCore):  
  On Windows, use: `adb shell pm dump com.google.ar.core | findstr /i "packages: versionName"`
  On macOS, use: `adb shell pm dump com.google.ar.core | egrep -i versionName\|packages:`
- Output of `adb shell getprop ro.build.fingerprint`: 

### STEPS TO REPRODUCE THE ISSUE
 1.
 1.
 1.

**Comment by sundaranandram** [comment]
I am facing a similar issue. Any insights into why this might be happening?

**Comment by eqgis** [comment]
Hello, is this problem solved now?

**Comment by kinjalbhavsar** [comment]
Can you try this api: https://developers.google.com/ar/reference/java/com/google/ar/core/Frame#getHardwareBuffer-

Please post your sample code here in case there's still an issue.

**Comment by eqgis** [comment]
Thx，I try it.
