### ISSUE TITLE
augmented images of slanted surfaces

### ISSUE THREAD

**Issue by michaelvogt** [google-ar/arcore-android-sdk#460]
I used so far augmented images on vertical signs. That worked so far.

Right now I am using it for a slanted sign, maybe around 30 degrees from horizontal. What happens now is, that the sceneform objects I place in the arfragment frequently rotate around the z achses. I have never seen this for vertical signs.

Can augmented images be used on slanted surfaces?

**Comment by michaelvogt** [comment]
I definitely do ask questions about Sceneform on the Sceneform side.

Given that this is a question about com.google.ar.core.AugmentedImage; supporting slanted surfaces or not, can you please explain how this question is about Sceneform and not ARCore?

**Comment by avirodov** [comment]
Sorry, I am reading:
> What happens now is, that the sceneform objects I place...

I see the word sceneform, and I infer that this is about Sceneform, am I misunderstanding?

**Comment by avirodov** [comment]
To answer the question about slanted images in android SDK specifically, I will confirm that the pose returned by com.google.ar.core.AugmentedImage is non-rotating for slanted images. Will reply shortly.

**Comment by avirodov** [comment]
I confirmed that the [Augmented Image java example](https://github.com/google-ar/arcore-android-sdk/tree/master/samples/augmented_image_java) behaves as expected on slanted surfaces (see image).

This may be a sceneform bug where Sceneform does additional computation on the pose provided by `com.google.ar.core.AugmentedImage.getCenterPose().` Please let me know if your observation about `com.google.ar.core.AugmentedImage.getCenterPose()` differs, and if not, please post this issue on the Sceneform bugtracker. Please let me know if I can help in any other way with this issue.

![image](https://user-images.githubusercontent.com/26363982/42068493-2065c9b8-7b01-11e8-9c2d-73875e8b39e0.png)

**Comment by michaelvogt** [comment]
I thought finger pointing and works for me as a engineering technique are extinct.

Also I wonder, how you could possibly see with your extensive, symetric testing setup if the objects do rotate around.

Here you can see a short video what the effect is:
https://drive.google.com/file/d/1Ot69sOUlIRn7YhvKTwmZM_VEw4Li3bzY/view?usp=sharing

PLease a serious answer if augmented images algorithm is working on slanted surfaces (real objects, not monitor). I see for example that plane detection doesn't work on such surfaces for me. 

Will create an issue for Sceneform as you suggested.

**Comment by avirodov** [comment]
> Please a serious answer if augmented images algorithm should be working on slanted surfaces

It should be working. You observe otherwise, hence I was debugging. Thank you for providing the video, this is very useful to see the issue in action. It will also be very useful to the Sceneform team.

I've confirmed with a less symmetric setup that at the android sdk level there is no issue. Note that Sceneform is a layer on top of android sdk that introduces additional logic, and my current guess is that the issue is in that additional logic. Please let me know if you have evidence to the contrary.

> real objects, not monitor

For better or worse, the system is not able to distinguish. The image on the monitor is as real as a printed one for ARCore.

> finger pointing and works for me

I was trying to get you to the team who can best help with the observed issue. I apologize for any misunderstanding this may have caused.

**Comment by michaelvogt** [comment]
Thank you for your answer.

As you mention it, that is what I was wondering a while already: the monitor image is of course always ideal (100% the same picture on the monitor and in the augmented image database), while the real image continually changes, based on influences from the weather for example, where parts of the image might become shiny through the sunlight or partially obstructed (dirt, leaves). Are you saying that this doesn't influence the recognition?

I realize that this question is not directly about this issue, but would be nice to get some advice for. Maybe have multiple images from an object in the augmented image database, taken at different time of day or season. Would that be a good idea?

**Comment by michaelvogt** [comment]
Thanks for your answer. Very helpful. 

Even after experimenting quite a bit with the arcoreimg tool, I still don't have a good feeling about what is considered good quality. For example when I open a marker image in an image processor and apply all the optimizations, arcoreimg gives this image a quality of 0. When I convert the same image to grayscale and remove the text, I get a result of 30. Increasing contrast of this image reduces the result to 10.

Using HelloAR to see the feature points ARCore recognizes is certainly a good idea, but it seems this doesn't work that well on the monitor, as in my case the image captured by the camera in is usually pretty blurred. So I was wondering, if arcoreimg could export an image showing the feature points that were recognized during evaluation instead just an abstract number. Just a thought.

Correct comandline for me for arcomeimg is on windows
`arcore-android-sdk/tools/arcoreimg/linux/arcoreimg eval-img --input_image_path=<your_image>`

**Comment by avirodov** [comment]
Hi, I tried to reproduce the issue with your target image, but no success, sorry ([video](https://drive.google.com/open?id=1UGD-mu0P6j09cbmIq_vkFcTjpBCev8Zn)). I used Pixel 2. Few things:

1. I [shared the apk](https://drive.google.com/open?id=12jsWoWV7IkYAsePwagWn7rBCUq9HQLjm) I used. Can you please use it on your device and see if it reproduces the problem? I added extra logging (pose of camera and pose of anchor as reported by the system), so if it does, can you please attach the logcat output, if acceptable? Feel free to sanitize on the "xxav" tag.

2. Can you please confirm you are using [ARCore 1.3](https://github.com/google-ar/arcore-android-sdk/releases/download/v1.3.0/ARCore_1_3.apk)? Just to make sure we're not observing but that is already fixed.

3. Do you have screenOrientation=locked? That's what is in the sample, but just confirming to reduce variables.

4. You mentioned "still happening when pointing to the respective image on the computer screen" in the other thread. To confirm, was the image slanted then? Or was it roughly vertical? Not sure it matters, just collecting data.

5. Can I please have a fingerprint of your Pixel2 device? `adb shell getprop ro.build.fingerprint`. Though if you have same issue on two very different devices, I would guess it is not device-specific.

Sorry for the run-around, but I don't have a good guess of what this issue may be, and I cannot reproduce it here. If you can suggest anything I could do differently to reproduce the problem, that would be welcomed.

**Comment by avirodov** [comment]
Another thing to confirm, can you please check you are using Sceneform 1.3? You should have in your gradle:
```
dependencies {
    implementation "com.google.ar.sceneform:core:1.3.0"
    implementation "com.google.ar.sceneform.ux:sceneform-ux:1.3.0"
...
}
```

Again, this is to make sure we are not looking at a fixed bug.

**Comment by michaelvogt** [comment]
Thank you for spending time for this problem.

Before making any changes, [here is what I see on my side](https://drive.google.com/file/d/1lRTKxSHmzwA0IBYLHI7SIBvNfcguPHaU/view?usp=sharing). I created a custom material for the lower left tile to see the rotation.

1. Unfortunately I wasn't able to install your app. Neither with the normal installer, which just reported that the app wasn't installed, nor with adb
adb.exe install ..\Downloads\app-release.apk
adb: failed to install ..\Downloads\app-release.apk: Failure [INSTALL_FAILED_TEST_ONLY: installPackageLI]

2. Yes, just deactivated and reinstalled to the latest version

3. I think so. I cloned the sceneform repo and just changed the filename for the single file to use, the flag to use the single file and today the custom material

4. Yes the screen was much steeper than the original infoboard, which is about 45 degrees. From testing, I see the problem more frequent on the infoboard on location than on the steeper screen. 
Just tried it out on a completely vertical screen, where the problem also shows up.

5. Sure: google/walleye/walleye:9/PPP4.180612.004/4838310:user/release-keys

6. Yes, Sceneform 1.3 is used in the sample

No worries, happy to help solve the problem in any way possible. I need this to be solved as with the rotation happening, augmented images is completely useless for me.

**Comment by avirodov** [comment]
1\. Can you please try again with `adb install -t app-release.apk`? Note the `-t`. (details [here](https://stackoverflow.com/questions/25274296/adb-install-fails-with-install-failed-test-only), I missed that this flag was introduced by Android Studio for local build).

5\. It seems you are on Android P (walleye:9). I'm wondering if this may be an issue, and I can try to reflash my Pixel2 on Monday to that exact fingerprint. If you have a supported Android Oreo (8) device handy, can you see if that also reproduces the issue? You also mentioned Asus device having a similar issue. Can I please have the fingerprint of that device?

7\. (new) How is tracking working in other ARCore apps on that device? I am wondering if this is somehow a device issue. You can get e.g. [Just a Line](https://play.google.com/store/apps/details?id=com.arexperiments.justaline&hl=en_US) or any other app, and see if the 3d objects that are not attached to images are behaving correctly.

**Comment by avirodov** [comment]
Yet another thing to try is to build the [android sdk augmented images sample](https://github.com/google-ar/arcore-android-sdk/tree/master/samples/augmented_image_java) with the same change you did [in this file](https://github.com/google-ar/arcore-android-sdk/blob/master/samples/augmented_image_java/app/src/main/java/com/google/ar/core/examples/java/augmentedimage/AugmentedImageActivity.java):
* change useSingleImage to true in line 83.
* change filename to office.jpg/office.png in line 386 in loadAugmentedImageBitmap() function.

To break the symmetry of the border, you can draw using any image editor on top of [frame_base.png](https://github.com/google-ar/arcore-android-sdk/blob/master/samples/augmented_image_java/app/src/main/assets/models/frame_base.png). That's what I did.

This will confirm that the issue is not in Sceneform, as Sceneform will be completely out of the picture in this experiment.

**Comment by michaelvogt** [comment]
1. I could install the app correctly with the -t flag, and also don't see the rotation happen with your app. I see that you have the .jpg file as the marker. Could you try with [this png file](https://photos.app.goo.gl/Jc4GraCLPGnsz6bX9), please. I suspect that has some influence.

5. I only have these 2 devices (Pixel and Zenfone) with me right now. Unfortunately, Oreo seems to be canceled for the Zenfone. Its fingerprint is
asus/WW_ASUS_A002/ASUS_A002:7.0/NRD90M/14.1600.1804.49-20180515:user/release-keys

7. Tracking on the Zenfone is generally more erratic than with the pixel. Meaning, the augmented content jumps more around also with other publicly available apps, but not to the extend I see here right now. Problems like the virtual objects flying away or acting completely erratic to the point of unusable happen only from time to time.

But, this was so far all apps where the user has to place the object on a plane. I haven't seen an app that uses augmented images with ARCore in the play store, yet.

With 'just a line' I had the problem that the tracking was lost easily. I've been inside with others surrounded with more or less blank walls, which is obviously hard for ARCore to keep the tracking.

I did some test yesterday around an anchored object walking about 100m and back. There was of course drift, but I thought that looked reasonable. This was done with the Zenfone.

Yes, the rotation is seen with the arcore augmented image sample app, too.  With both devices and png file as marker using picture on screen. [Here is the video](https://drive.google.com/file/d/1yZqq6wXJA1bSHRjsuWNVZN0GV0pSumkT/view?usp=sharing).

Didn't happen with the jpg file as marker. Will be on location later next week to confirm there.

**Comment by avirodov** [comment]
I got the issue to reproduce. I think I see the problem. You have two images that are very similar (office.png and office.jpg), and I got it to reproduce when I pointed the device to the "other" image (not the image that is embedded in the app). 

At this point I am not sure if this is a bug or a limitation of the system. I will investigate further. Can you please confirm that when you point your app to the "right" image, it works as expected, and you see the problem only when you point your app to the "wrong" but similar image?

More detail: I embedded "office.png" in the sample app. I have "office.jpg" printed out. When I point my app to "office.png" on my screen, it works. When I point it to the printed version (slanted), I can see the rotations if I move around enough.

**Comment by avirodov** [comment]
One workaround for this issue is to cut out the right part of the image (the one that is different), if acceptable for your app. If you prefer to keep full image dimensions, you can white-out the different part so that it doesn't contain any features for the system to pick up.

I tested with this image, and it seems to work correctly for me:
![office_whiteout](https://user-images.githubusercontent.com/26363982/42467025-9c32523e-8365-11e8-9bc9-3a35d75fc07c.png)

**Comment by michaelvogt** [comment]
I see, makes sense. It's not the slanted surface that is the problem here after all. Good!

Thank you for your suggestion. It is good to know that ARCore could handle augmented images with edits like this. In this particular case, arcoreimg reports a quality score of 0, though, which probably prevents the image to be imported to the augmented image database.

As I need to distinguish between the 2 info boards anyways, I now imported both marker images to the database, which resolves the rotation problem on both sides. 

That seems like solving the problem for me. Thank you for your patience.
