### ISSUE TITLE
Create anchor method not working

### ISSUE THREAD

**Issue by subhamC** [google-ar/arcore-android-sdk#610]
if I use session.createanchor(pose) only with a pose without any trackable it drifts away and moves with the camera only rotation is taken into consideration .But in the preview version of arcore (arcore preview2 sdk) there is a method called session.createworldanchor(pose) which does the same exact thing but it works when the user moves the position of the device forward and backwards. in the newer version there is this error.

**Comment by inio** [comment]
`Session.createAnchor()` is just a renamed version of the DP2 `createWorldAnchor`.

Do you get any plane detections (HelloAR shows these visualized with a triangular pattern)?

What device are you on?  What is the output of `adb shell getprop ro.build.fingerprint`?

**Comment by subhamC** [comment]
yes everything works fine if i put a trackable there. i am on poco f1 so what should happen if we create a anchor without a trackable ?But i want it without the trackable. Its getting bit confusing check out these videos 

https://drive.google.com/open?id=1OXRAjsBu2CgM4EgTu8hUITWUOLF2Lp1o

**Comment by subhamC** [comment]
one video is with preview sdk another is with sdk 1.5 why there is this difference in behavior i dont know

**Comment by subhamC** [comment]
the object is not getting scaled if i move forward

**Comment by subhamC** [comment]
if you want both apk i can send both of them as well

**Comment by subhamC** [comment]
the issue is also there on pixel

**Comment by inio** [comment]
So I just took the HelloAR sample and replaced the line

    anchors.add(new ColoredAnchor(hit.createAnchor(), objColor));

with

    anchors.add(new ColoredAnchor(session.createAnchor(hit.getHitPose()), objColor));

I observe that the anchors now do not update in height as the plane estimation changes, but otherwise work fine.

**Comment by subhamC** [comment]
ok thanks man good to know is fixed so fast

**Comment by inio** [comment]
I didn't fix anything, just tested that it's working correctly.

**Comment by subhamC** [comment]
Then how come its not working for me i sent you videos did you see them

**Comment by subhamC** [comment]
the anchor needs to be near a trackable to have stability and if the trackable is null it just moves with the camera you try to create a anchor without trackable and send me the video if you have stablity

**Comment by subhamC** [comment]
dont use hit drirctly do session.createanchore(new pose(cam.transform.pos,qrutonien.identity)) make a object child of this anchor in both sdk
1.5 and preview2 and see the difference for yourself

**Comment by inio** [comment]
Closing for inactivity.
