### ISSUE TITLE
Xiaomi: add support for CPU image access

### ISSUE THREAD

**Issue by rikudoxx** [google-ar/arcore-android-sdk#683]
I am looking to get an Android device to try ARCore development for the first time. I had my eyes on the Pocophone but in the list of compatible ARCore devices (https://developers.google.com/ar/discover/supported-devices) there is a comment for all Xiaomi's devices that there is "No support for CPU image access".

I have found any information on what that means on how will limit me and affect me.

Can anybody explain this limitation?

**Comment by sebastianoscarlopez** [comment]
Could someone explain this limitation, please?

**Comment by inio** [comment]
It means that the Frame.acquireCameraImage() API will always throw NotYetAvailableException.

Unfortunately on these devices, when an ImageReader and SurfaceTexture are connected to the camera, frames are delivered to the ImageReader as much as 100ms after being delivered to the SurfaceTexture. Our motion tracking can handle this (you just get 100ms more IMU integration), but it prevents us from providing synchronized textures and CPU images.

**Comment by gkscorpio** [comment]
Could anyone post an example in which continuous image processing would be necessary? Or any other example in general where this limitation is truly crucial?

I don't suppose this is a hardware issue though, maybe it will be fixed with a software update sometime soon.

**Comment by michaelvogt** [comment]
Yes, this feature is very important to offer really useful AR functionality, as ARCore is way too limited, and not updated for much too long. Even the existing features are pretty basic. 

I think this article shows some interesting things to do with camera access:
https://augmented.org/2018/12/mask-fusion-to-let-ar-learn-about-the-worlds-objects/

**Comment by shliama** [comment]
@gkscorpio for example, scanning for QR-code in parallel using 3rd party SDK

**Comment by shliama** [comment]
Well, it seems like we won't get this feature fixed (or rather "enabled"), is there a way to know if a device supports `Frame.acquireCameraImage()` API? I need to know that before I enter the "camera" screen.

Even if I could try to call `Frame.acquireCameraImage()` and check for `NotYetAvailableException` - it will hardly help, since even in your sample code there are these lines

```
...
try {
    frame.acquireCameraImage()
    ...
} catch (e: NotYetAvailableException) {
    // This exception will routinely happen during startup, and is expected.
}
````
So how can I differ whether it's "routinely/expected" exception or Xiaomi "special" behavior :(

P.S. Easy answer - blacklist all Xiaomi devices.

**Comment by shliama** [comment]
@inio In release notes v1.8.0 it says `Fixed CPU Image Access on Xiaomi devices: Mi 8, Mi 8 SE, Mi Mix 2S, Mi Mix 3 and Pocophone F1.`
So does that mean we have support for CPU image access? I don't see any changes on supported devices page https://developers.google.com/ar/discover/supported-devices

**Comment by shliama** [comment]
Okay, the supported devices page was updated yesterday, so I think Xiaomi issue has been fixed. That's awesome 👍

**Comment by fredsa** [comment]
Fixed in ARCore SDK 1.8.0

**Comment by ls29322** [comment]
I think the error is back in SDK 1.11 :( (at least on my pocophone!)

**Comment by flankechen** [comment]
@fredsa is this  related to sdk not google play services for ar?
I have mi 9, google play services for ar 1.16 installed, still getting this problem
